<a href="https://colab.research.google.com/github/MarcosACVieira/geral/blob/main/Definitivo_vPreverHoje.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from keras.layers import LSTM, Dense, Dropout,SimpleRNN,Conv1D,MaxPooling1D,Flatten
from keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
from datetime import datetime
from dateutil.relativedelta import relativedelta
from urllib.request import urlopen
from zipfile import ZipFile
from io import BytesIO
from datetime import timedelta
import time
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
btg = ['11435287000107','29982932000169','16839141000132','41992740000139','26112022000137','27923072000167','42730970000192','29993579000112','39800632000175','35744790000102','45294958000170','32892819000105','26680221000141','05488919000190','13812165000100','31556580000121','39958394000120','35726581000128','37308317000108','12105940000124','28581119000114','39345935000145','35343590000130','18832871000137','38048878000170','04192419000143','22899381000125','19366052000104','23966345000108','13823084000105','33599991000120','22353918000157','03593195000119','42730755000191','38949124000190','37098846000116','31493876000140','38028730000173','26277600000195','12047839000164','01522368000182','18719154000101','28798135000163','23729562000176','39913737000130','37953241000165','36498670000127','45294999000167','62418140000131','09083868000177','20584638000124','32041623000107','38318178000158','07539298000151','29853005000149','17102710000125','03319016000150','22672424000135','22354046000141','00836263000135','27347332000101','26587503000107','41544075000110','32471624000183','26623196000164','26262377000102','34473526000100','36492413000188','14146726000141','07187751000108','42826922000100','29599922000149','37368078000173','14237118000142','31690716000191','36498353000100','23951048000180','08912569000135','43095852000112','10705335000169','37287717000176','33158068000152','29054797000191','27528774000146','28075437000103','19488768000184','27928186000108','17447468000121','09326708000101','37504085000155','39991941000170','35727276000150','23729512000199','26305892000122','29177024000100','33361798000156','09814233000100','41065292000128','35088117000153','39958460000162','26324209000102','23272391000107','41745741000189','40575693000165','11182064000177','13615411000133','30556738000109','20146294000171','41993440000174','11392165000172','01214092000175','37712284000159','43584490000123','32295478000182','42731202000153','07381653000107','43508943000132','12923406000125','12565159000132','12440825000106','43984537000146','10500884000105','43778868000120','35343836000173','37018336000191','30910553000142','08323402000139','26142614000100','34799112000176','20055468000190','41745133000174','22003375000148','41088640000182','07124064000143','35618055000144','34979903000188','18889810000106','17787909000134','12239939000192','38065069000176','36352424000162','21946695000179','29206165000104','24140256000162','29286406000164','15912241000184','37498652000108','39703177000190','25213405000139','46300375000178','31455960000170','25423226000126','44980432000181','42730726000120','31416575000113','41969176000133','36352554000103','22344843000148','41969763000122','24592505000150','18391171000154','31923988000194','27826059000190','09441308000147','31923761000149','20468028000165','17898650000107','05092270000193','40428039000129','41252582000180','38281372000106','29587389000103','35420451000162','30317454000151','00888897000131','34979818000110','17816013000136','41063334000191','30005655000113','38049303000171','41373608000149','44209582000196','16987508000165','36249284000100','12004203000135','41373588000106','45126981000156','42081209000177','36014075000179','44515610000101','16816153000141','41088682000113','17033928000175','11701985000107','19941946000180','35957054000124','08968733000126','30593403000152','09087523000191','30858733000122','19488866000111','42922205000174','45126795000117','17313316000136','44515852000197','43508005000132','15569128000148','39456513000147','43096273000194','31964074000171','22344837000190','29283824000106','38443033000189','40141547000121','30057258000195','43984912000158','32319558000120','36248844000101','28581159000166','36017669000133','40102910000108','04501865000192','18391138000124','44602950000161','02162620000152','40920066000114','36521802000194','30077777000115','17164804000129','42887842000157','43508446000134','39511032000197','28320600000156','41266158000195','31353372000125','07013315000112','17414721000140','11447124000136','18628905000176','33361657000133','21185984000100','35432385000140','31120420000135','43214636000149','34096227000102','29994491000115','06301947000119','11741429000156','32158410000151','19628666000117','20824446000148','34096132000180','12154412000165','23960625000109','44209661000105','41266134000136','09518581000122','33600729000158','05892566000199','38064885000165','35609273000112','09120774000120','33144687000198','17340392000130','35372675000146','32973321000169','37310657000165','45682022000117','41044877000161','38049108000141','15334585000153','40716583000176','23872712000104','04455632000109','10447046000107','35345237000199','40265199000102','24572582000149','19831126000136','43508596000148','32754593000178','28320626000102','34096240000153','07187591000105','17759778000181','41484468000186','30995018000131','26525450000191','18316558000146','09720734000110','30294098000106','21624757000126','29186346000108','36318507000135','31248342000159','33824951000134','09290813000138','29286399000109','34218763000125','02895694000106','30630299000129','34096235000140','19719727000151','18679873000138','37567415000151','09636393000107','05862906000139','12796232000187','10326625000100','22773406000140','17547247000125','43915574000100','39293607000142','35726720000113','02603461000184','29044189000104','35828684000107','41483966000104','41594555000196','13054728000148','26434293000109','14799785000119','40265153000185','43140576000167','36498594000150','26370126000141','34096113000154','38026540000117','04899128000190','26648868000196','41755418000196','26362460000153','12987743000186','15862830000103','26978438000132','28558421000151','27783868000161','14188162000100','18860059000115','38377278000155','39293641000117','34713026000107','36327569000103','37567202000120','37013129000144','44209755000176','41594333000173','20879578000177','26768800000140','42747231000103','00817677000117','22710616000199','43103846000160','44489547000178','40265128000100','42730566000119','30509286000104','30910199000156','29283812000173','11186674000149','35939847000110','35625272000161','11111063000131','35342982000184','24492354000169','42119554000152','42774128000152','10783480000168','36326860000167','19782311000188','08771538000101','32158430000122','31922843000179','10643371000145','26673556000132','33361831000148','31964457000140','19418031000195','14806166000104','12287682000144','38318112000168','38026926000129','21329166000126','43140671000160','32760042000117','39835826000106','22662135000155','32227355000104','28747685000153','29066331000106','34831155000191','36015100000139','19212817000151','45295229000139','27546616000119','35820605000103','21917184000129','45126846000100','33925183000105','34109809000178','44614202000107','26841302000186','11952873000110','11447136000160','36352596000136','38318005000130','29196922000106','29206196000157','00840011000180','32236763000122','07279657000189','41287933000199','21006934000100','21732619000160','26773148000152','32073525000143','41673246000101','39281097000193','07899238000140','37887638000104','23686321000197','40936530000160','27717359000130','20374752000120','34431415000131','32228412000170','12082452000149','26369994000101','41771697000181','29993583000180','14083797000142','32225478000106','09543255000175','35725802000143','44479850000190','12923387000137','38948507000144','23711486000171','23714047000112','22759995000101','35471498000155','34475094000177','33824820000157','41559595000105','46246485000107','40660810000199','05969595000101','34780531000166','44479860000125','36728106000153','38029012000111','34781162000126','38173769000184','41163392000197','34054867000141','13974750000106','25423215000146','17797426000110','11108013000103','33378392000186','29177012000178','22100009000107','35726908000161','37495438000106','35088108000162','32397723000162','26396708000105','34626199000180','39435574000128','30773631000104','11052478000181','31533145000181','30593439000136','19773986000160','26269603000187','42773832000190','26243348000101','26218614000138','09068336000160','30568854000130','00601692000123','23186344000132','11228311000129','13396703000122','13083227000190','32893639000130','30995398000104','38971881000160','26831986000135','08892340000186','12845796000162','10608762000129','38597242000187','06041290000106','32295931000150','39958357000112','17453850000148','34774662000130','43214601000100','38954217000103','42730656000100','29826089000121','23243536000133','40920230000193','44026806000124','18525868000170','41888275000190','43917039000180','11182072000113','12430199000177','10347249000121','39957930000173','37467515000106','40503169000189','13476201000101','15578417000103','10237480000162','08830947000131','30995144000196','00947958000194','36986672000165','41922498000127','39737102000120','32743215000199','28077946000175','40102306000173','23695876000103','15799713000134','42084858000121','30338679000194','21646715000196','31440882000130','29762315000158','07088369000147','27707783000102','34172497000147','00400490000113','35636909000115','08279304000141','43274439000115','20226378000115','37828294000154','33736845000107','28246652000120','24140265000153','21983042000160','36499625000197','28866524000189','03119883000141','35535649000191','42480017000133','44613740000179','41922414000155','15390811000113','14866273000128','35408329000170','20658576000158','32102131000176','41545099000194','09586692000176','42190534000178','36327622000176','22681798000117','36499594000174','31594537000150','29127763000180','28581175000159','37495383000126','40226025000122','45126753000186','25213366000170','43214564000130','30282227000138','01823373000125','22918359000185','43164374000155','26323079000185','36352498000107','07266253000150','36181846000112','44417227000102','10320188000109','09635172000106','17400251000166','43507873000106','03168062000103','41907541000185','18471807000178','41081041000137','35646163000120','29762329000171','20458815000126','40102191000117','17335646000122','26370141000190','29286347000124','26623189000162','18623722000168','34286544000183','17554200000199','09401978000130','20501983000157','40916758000199','44347311000105','35956906000169','05448587000110','31326427000108','34218748000187','23556185000110','14812722000155','05109839000186','37093442000130','12282747000169','33736873000116','09720710000160','11628883000103','19821469000110','24454718000116','39990463000183','19628842000110','29562563000155','00066670000100','01599628000118','02782911000143','03068246000193','03507873000183','04223291000138','04244149000177','04812385000142','05936530000160','07400556000114','07488106000125','07584202000177','07892305000102','08056837000164','08154725000146','08767024000182','09412648000140','09520697000104','09911412000158','10841406000150','11403956000150','11898349000109','11904064000133','11918575000104','11977794000164','12219414000195','12483978000130','14171644000157','14438229000117','14843272000168','15037554000130','15629805000176','15714222000143','16565016000181','16929562000154','17138445000135','17248340000139','17295128000122','17329742000168','17408524000119','17429959000140','17430334000106','17472972000181','18000082000130','18265951000158','18324938000122','18868875000175','18999402000107','19154041000160','19589972000191','19602004000178','19726267000199','20056368000189','20056898000127','20391600000135','21689246000192','21762085000115','21934992000102','21964701000110','22188059000198','23502654000119','24140338000107','24774103000177','25108905000100','25108971000180','25306476000186','25306735000179','26406529000101','26580293000117','26831831000107','26913920000194','27181717000133','27181765000121','27381541000163','27566556000104','27717327000135','27739565000141','27751295000194','27782855000178','27943626000198','28075532000107','28078762000120','28140746000110','28470595000168','28750204000169','29177909000100','29224629000105','29226523000132','29258294000138','29544764000120','29562673000117','29574911000104','29726019000100','29853075000105','29954052000189','29983486000107','30178843000143','30294047000176','30338686000196','30493304000107','30530779000118','30652395000178','30658543000161','30934728000151','30934757000113','31340838000158','31340883000102','31523678000182','31525297000132','31611434000151','31846723000130','31961936000102','32162788000129','32190556000184','32295829000155','32312046000132','32312124000107','32386474000100','32386727000145','32388012000121','32665845000192','32666303000134','32757330000112','32783564000134','32841087000116','32849785000168','32905287000195','32905367000140','32972925000190','32990098000168','33388296000119','33389246000156','33435749000110','33499192000181','34081031000136','34109752000107','34109764000131','34123522000100','34258661000133','34286706000183','34429833000194','34430477000129','34431537000128','34474989000197','34687441000125','34791108000161','34793170000192','34839385000105','34839814000136','34979736000175','35002927000145','35088081000108','35343483000101','35354967000156','35400140000131','35420795000171','35420976000106','35488313000115','35491437000150','35495418000100','35495706000156','35505971000178','35578945000170','35591389000171','35672048000120','35672208000131','35711448000106','35726822000139','35844770000103','35847977000123','35848011000100','35848046000140','35848055000130','35848058000174','35848062000132','35940266000107','35955929000159','36014054000153','36249375000137','36327493000116','36429849000122','36436794000188','36619783000133','36619937000197','36620118000160','36620345000195','36671926000156','36673471000108','36988916000149','37110068000133','37248132000147','37280206000122','37281872000185','37282299000124','37287622000152','37347946000139','37355327000196','37367803000199','37368116000198','37404820000159','37405108000174','37437010000107','37487500000100','37487768000141','37510387000136','37510734000120','37525962000174','37554478000173','37565243000187','37569846000157','37590561000106','37654093000188','37729228000127','37978226000171','38001966000116','38032741000127','38058097000166','38120941000131','38145457000167','38173778000175','38248976000150','38267814000160','38281316000171','38281467000120','38306286000100','38315751000170','38330383000139','38657534000168','38657612000124','38860552000142','39272568000105','39281341000118','39518356000157','39573883000164','39586848000180','39807251000118','39807296000192','39816755000102','39914028000170','39973671000174','40209475000107','40226091000100','40226121000170','40265177000134','40575673000194','40653167000176','40903923000178','41054588000143','41196740000122','41215368000154','41276111000102','41326212000140','41333223000158','41333373000161','41342568000178','41350825000113','41360263000199','41569995000193','41594603000146','41594807000187','41594835000102','41672258000111','42046773000159','42084936000198','42085026000120','42132653000174','42190567000118','42190664000100','42281839000195','42315695000140','42405028000159','42428306000193','42698615000183','42730789000186','42731236000148','42831231000197','42878365000163','42888072000167','42922224000109','42922247000105','43122432000188','43164393000181','43508091000183','43761719000158','43761750000199','43915616000103','43917493000131','43985477000186','44100909000197','44315854000132','44315861000134','44315932000107','44347394000124','44642691000100','44903461000140','44967234000188','45560980000115','45605070000101','45664086000195','45682095000109','46133800000181','46205854000105','46385232000106','46391457000175','46442453000179','46521638000179','46729405000166','46929841000189','47212318000108','47539700000112','47540269000124','47548587000131','47586648000155','47612663000120','47612737000129','47675912000127','47731566000157','47756349000111','47812154000141','47812171000189','48045735000168','48084411000139','48096240000168','48132791000130','48132888000142','48263105000160','48554229000102','49226150000107','49304814000109','49307394000114','49425680000184','49429025000102','49624023000166','49731753000166','49793563000173','56824857000180']


xp = ['34774642000160', '29044189000104', '9720734000110', '41888219000156', '30921203000181', '32319627000104', '39959156000130', '35789436000196', '6041290000106', '32225663000109', '3168062000103', '10237480000162', '41888191000157', '17414721000140', '41888492000180', '39737102000120', '32240069000189', '34370777000160', '7279657000189', '25213405000139', '9141893000160', '34187244000147', '4455632000109', '26323079000185', '11392165000172', '36352498000107', '13974750000106', '22681798000117', '19782311000188', '16599968000116', '10320188000109', '29813769000100', '35617938000130', '18860059000115', '32892827000143', '28947266000165', '31392865000174', '24078037000109', '29298529000115', '23979285000150', '12987743000186', '26673556000132', '36352721000108', '34839385000105', '15862830000103', '40634864000180', '38377278000155', '33345956000184', '21689246000192', '20458815000126', '38452175000102', '37567365000102', '23186344000132', '41544414000169', '34218678000167', '30568495000110', '39293641000117', '35844973000191', '38443033000189', '5104498000156', '9636393000107', '2539921000152', '21185984000100', '11108013000103', '42888147000100', '42888163000100', '1430938000104', '11952873000110', '7539298000151', '32862354000131', '35844932000103', '28747733000103', '9635172000106', '41333093000153', '33422090000168', '30056825000199', '28504521000103', '33361831000148', '33361657000133', '32319396000120', '34054884000189', '34109809000178', '7187751000108', '34430477000129', '37895324000145', '18316558000146', '15350679000116', '35726300000137', '41196241000135', '6070574000112', '28246652000120', '41075440000195', '34431610000161', '28866524000189', '26605199000175', '20146294000171', '23272391000107', '37108174000182', '13615411000133', '23957096000186', '11447136000160', '17302010000184', '39293724000106', '39286576000100', '39960120000176', '10705335000169', '37108084000191', '27944406000189', '31416575000113', '39959828000107', '11403850000157', '35408329000170', '36352596000136', '34462109000162', '40920066000114', '35432385000140', '33755672000166', '34309551000153', '10783480000168', '34626199000180', '17251743000137', '22652091000182', '37487547000173', '37487500000100', '36318544000143', '19628666000117', '601692000123', '21917184000129', '37887638000104', '40212731000115', '30294047000176', '2895694000106', '27528774000146', '18832871000137', '41065292000128', '42279385000118', '42287556000150', '36327569000103', '29853005000149', '38281467000120', '42287819000121', '1823373000125', '35717650000137', '26179685000179', '37893341000143', '10447046000107', '25307278000137', '26434293000109', '31608422000178', '39317019000100', '36017731000197', '28075532000107', '32102192000133', '36352424000162', '41075713000100', '41888252000186', '43422751000109', '34186116000189', '35940266000107', '11052478000181', '41610489000109', '37525962000174', '42750164000186', '37525911000142', '18889810000106', '8830947000131', '32240637000141', '30556738000109', '32890800000111', '22662135000155', '33736845000107', '33736873000116', '35088108000162', '36986672000165', '38954217000103', '12082452000149', '35939847000110', '5936530000160', '37310657000165', '26243348000101', '12154412000165', '30493349000173', '17554200000199', '29732926000153', '41545099000194', '8279304000141', '12682783000110', '7400556000114', '34793170000192', '19418031000195', '35646163000120', '17335646000122', '26978438000132', '28259415000101', '32756812000158', '19628842000110', '24454718000116', '29587389000103', '26112046000196', '19821469000110', '23956069000199', '28767162000179', '36352690000195', '9143318000104', '11228311000129', '28648924000118', '30190210000150', '41594333000173', '43121036000136', '34580935000106', '31120420000135', '33150386000177', '43778868000120', '14146496000110', '9441308000147', '33378392000186', '31455960000170', '31923761000149', '32783564000134', '28849694000155', '33520968000106', '39573883000164', '39375554000109', '43103187000161', '29762315000158', '21624757000126', '35372675000146', '39586835000100', '32990051000102', '41219331000102', '27945264000174', '42731202000153', '27749572000124', '25213366000170', '29054793000103', '24325422000103', '10320151000180', '26768800000140', '30566221000192', '39487197000170', '40107402000104', '34579122000104', '11182072000113', '8869576000100', '39959357000137', '29762338000162', '8610270000126', '32397723000162', '38049108000141', '38049303000171', '30773649000106', '39506138000100', '38444096000150', '32236915000197', '35354967000156', '41326095000115', '24140256000162', '31392336000170', '38001966000116', '29283824000106', '32228412000170', '19488768000184', '11435287000107', '19392834000118', '15585932000110', '19186860000190', '26396708000105', '34793078000122', '32236875000183', '8771538000101', '26218614000138', '26324209000102', '28911598000190', '37467515000106', '21312739000109', '6301947000119', '14146726000141', '30995398000104', '39958195000112', '39958357000112', '38267707000131', '11403956000150', '11628883000103', '15578417000103', '35714550000157', '34475592000110', '17162002000180', '33401080000146', '13083227000190', '36182298000145', '31392506000117', '23915589000153', '18471807000178', '947958000194', '13106983000197', '5448587000110', '17400251000166', '29066331000106', '32225478000106', '23729512000199', '34799112000176', '14083797000142', '41888172000120', '17002861000101', '38252499000105', '24140265000153', '34096132000180', '39581595000151', '31594537000150', '41063386000168', '9068336000160', '10608762000129', '32041825000140', '31455879000190', '23601467000192', '27347332000101', '11228500000100', '7013315000112', '2603461000184', '18719154000101', '398561000190', '35378376000119', '21625026000103', '400490000113', '17787909000134', '11451917000129', '22918359000185', '27928186000108', '29206196000157', '29196922000106', '31506482000180', '21732619000160', '42847408000143', '40102306000173', '41088682000113', '35002599000187', '39958274000123', '34706586000126', '27783868000161', '41153236000145', '20468028000165', '26362460000153', '10500884000105', '28911549000157', '36436794000188', '36498670000127', '43917493000131', '36498149000190', '42260903000151', '16565056000123', '24215286000190', '24193691000155', '41342497000103', '28653850000108', '35648999000164', '37069872000116', '12282747000169', '17164804000129', '31533638000111', '31961612000174', '24018821000113', '37539419000126', '37405108000174', '38032741000127', '35744790000102', '37887412000103', '17898650000107', '33497084000170', '38029012000111', '18772290000157', '34583819000140', '26759909000111', '32757330000112', '12923387000137', '32846811000102', '14188162000100', '38026926000129', '38377471000196', '38377512000144', '40011415000185', '42774128000152', '17301119000105', '11225767000135', '17797493000135', '13823084000105', '33701828000126', '11458144000102', '12839769000187', '4899128000190', '4839017000198', '9326708000101', '22759995000101', '16892116000112', '24325096000126', '7381653000107', '906044000185', '41681126000156', '24140275000199', '34428006000186', '34429833000194', '31533145000181', '26269603000187', '26277595000110', '30830162000118', '26261488000102', '35471498000155', '40575693000165', '34096201000156', '43985426000154', '30509221000150', '10326625000100', '25213355000190', '17313316000136', '7088369000147', '23243536000133', '37013129000144', '34831155000191', '31403590000127', '39992517000140', '24572582000149', '22150467000150', '40226014000142', '12440825000106', '12287682000144', '35636909000115', '13396703000122', '28581039000169', '30593403000152', '28581109000189', '41409831000107', '34687441000125', '21329166000126', '30057258000195', '36352590000169', '40920005000157', '836263000135', '9344799000108', '3319016000150', '42014125000110', '41326212000140', '41409952000140', '41978534000174', '41409927000167', '28320600000156', '26369994000101', '19831126000136', '819889000133', '17517577000178', '7672392000184', '23872712000104', '22773406000140', '5024659000100', '4192419000143', '3499367000190', '28320756000137', '17453850000148', '9087523000191', '35377390000106', '38648589000101', '34231926000100', '34231958000105', '31392557000149', '34231938000134', '42291928000112', '40951903000172', '35002482000101', '38648362000166', '35002463000177', '35142453000137', '40750982000153', '40140521000169', '29298535000172', '38421193000127', '43216244000119', '43216216000100', '35557650000117', '35602471000154', '36554687000154', '37331264000138', '37980028000142', '39602975000125', '40755165000198', '38597751000100', '38597826000152', '40753313000135', '40753759000160', '37980142000172', '39468983000120', '39602901000199', '37627843000122', '42870785000101', '37626852000107', '35956056000107', '37645550000178', '35956153000191', '35999323000115', '42279908000126', '43105417000121', '43122432000188', '37985588000190', '39602824000177', '40887546000120', '40887476000100', '38428156000140', '38421502000169', '38597714000100', '39468864000178', '37985879000188', '38077340000193', '38596112000120', '38596762000175', '35433031000110', '36046327000141', '40884541000144', '40140447000180', '39466946000183', '39468702000130', '42280143000144', '42280094000140', '37489109000144', '37331214000150', '32386581000138', '32756019000159', '40755318000105', '40155341000150', '33913562000185', '38542735000110', '37489281000106', '20485402000130', '42101973000167', '40886337000162', '40887300000159', '39818102000154', '39602877000198', '39723190000100', '39603050000107', '39819658000165', '43105489000179', '40952286000120', '31403572000145', '42776552000136', '38221605000185', '39736976000162', '32889197000158', '37108017000177', '24582422000180', '35939801000100', '24582449000173', '39726116000148', '39726093000171', '30518346000147', '39726030000115', '34957512000162', '24572219000123', '39723347000106', '39723244000138', '35625840000124', '42228062000103', '42279852000100', '42288304000146', '43105361000105', '36327455000163', '31874833000105', '31145826000172', '35717740000128', '40212852000167', '40212899000120', '39227204000103', '37553464000135', '34218740000110', '41888517000146', '42776301000151', '40212817000148', '43105341000134', '32893503000120', '42407958000141', '42407900000106', '42479462000183', '42403384000133', '31132386000119', '37396815000141', '37108062000121', '40212831000141', '38597202000135', '37396932000105', '31936857000141', '31204199000101', '37552975000132', '31145833000174', '34475424000124', '38026814000178', '37887464000171', '44431925000162', '40212883000118', '35609786000123', '22963439000152', '38229922000148', '38027135000113', '31145851000156', '26559284000144', '37895175000114', '42776707000134', '32246789000151', '35956046000163', '32319351000156', '40212842000121', '42403085000107', '38057650000146', '38542779000140', '38542816000110', '38443120000136', '38443098000124', '38542686000115', '38443169000199', '38077221000130', '38077268000102', '42101922000135', '42101954000130', '38610795000122', '38597203000180', '35556444000192', '35578709000153', '32203189000106', '11046179000134', '23999611000190', '4621721000170', '22003930000131', '29813596000120', '27227796000176', '41610479000165', '19657463000159', '26803233000116', '36327149000127', '14146491000198', '26718169000175', '37466946000158', '28122142000140', '30869315000130', '21827663000154', '33755581000120', '23922063000109', '26549933000126', '34867766000190', '30068713000158', '10843445000197', '43120744000152', '34081651000175', '41888464000163', '39959974000132', '41901199000106', '41127229000179', '42776634000180']

# cnpjs target
btg = list(set(btg))
btg_ok = []
for cnpj in btg : 
  if len(cnpj) < 14:
    cnpj = cnpj.zfill(14)
  btg_ok.append('{}.{}.{}/{}-{}'.format(cnpj[:2], cnpj[2:5], cnpj[5:8], cnpj[8:12], cnpj[12:14]))
btg = pd.DataFrame({'CNPJ_FUNDO': btg_ok, 'Banco': 'BTG'})

xp = list(set(xp))
xp_ok = []
for cnpj in xp : 
  if len(cnpj) < 14:
    cnpj = cnpj.zfill(14)
  xp_ok.append('{}.{}.{}/{}-{}'.format(cnpj[:2], cnpj[2:5], cnpj[5:8], cnpj[8:12], cnpj[12:14]))
xp = pd.DataFrame({'CNPJ_FUNDO': xp_ok, 'Banco': 'XP'})

btg_exclusive = btg[~btg['CNPJ_FUNDO'].isin(xp['CNPJ_FUNDO'])]
xp_exclusive = xp[~xp['CNPJ_FUNDO'].isin(btg['CNPJ_FUNDO'])]
inter = xp[xp['CNPJ_FUNDO'].isin(btg['CNPJ_FUNDO'])]
inter['Banco'] = 'XP/BTG'
cnpjs_target = pd.concat([btg_exclusive,xp_exclusive,inter])
cnpjs_target = cnpjs_target.reset_index(drop=True)
cnpjs_target.to_csv('/content/drive/MyDrive/cnpjs.csv', sep=',')

<ipython-input-2-696bea656181>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inter['Banco'] = 'XP/BTG'

In [ ]:
names = pd.read_csv("https://dados.cvm.gov.br/dados/FI/CAD/DADOS/cad_fi.csv", encoding = 'iso-8859-1', sep =';', on_bad_lines='skip')
names = names[names['CNPJ_FUNDO'].isin(cnpjs_target['CNPJ_FUNDO'])]
names = names.groupby('CNPJ_FUNDO', as_index=False).first()

mask = (names['DENOM_SOCIAL'].str.contains("COIN") |
names['DENOM_SOCIAL'].str.contains("CRIPTO") |
names['DENOM_SOCIAL'].str.contains("CRYPTO") |
names['DENOM_SOCIAL'].str.contains("HASHDEX") |
names['DENOM_SOCIAL'].str.contains("BLOCK") |
names['DENOM_SOCIAL'].str.contains("NFT") |
names['DENOM_SOCIAL'].str.contains("CHAIN"))

names['CRYPTO'] = False
names['CRYPTO'][mask] = True

<ipython-input-3-d3d3aa47d13f>:1: DtypeWarning: Columns (14,17,18,20,22,24,27,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  names = pd.read_csv("https://dados.cvm.gov.br/dados/FI/CAD/DADOS/cad_fi.csv", encoding = 'iso-8859-1', sep =';', on_bad_lines='skip')
<ipython-input-3-d3d3aa47d13f>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  names['CRYPTO'][mask] = True

In [ ]:
df_all = pd.DataFrame()
months = 12
for i in range(months) :
    i=i
    currentTimeDate = datetime.now() - relativedelta(months=i) #- timedelta(days=1)
    currentMonth = currentTimeDate.strftime('%Y%m')
    url = "https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_" + currentMonth + ".zip"
    print(url)
    resp = urlopen(url)
    myzipfile = ZipFile(BytesIO(resp.read()))
    mycsvfile = myzipfile.open("inf_diario_fi_" + currentMonth + ".csv")
    df = pd.read_csv(mycsvfile, sep = ';')
    df = df[df['CNPJ_FUNDO'].isin(cnpjs_target['CNPJ_FUNDO'])]
    df_all = df_all.append(df)


df_all = df_all.merge(names, on='CNPJ_FUNDO', how='left')
df_all = df_all.merge(cnpjs_target, on='CNPJ_FUNDO', how='left')

https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_202303.zip

<ipython-input-4-f9de91239a30>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)

https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_202302.zip

<ipython-input-4-f9de91239a30>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)

https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_202301.zip

<ipython-input-4-f9de91239a30>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)

https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_202212.zip

<ipython-input-4-f9de91239a30>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)

https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_202211.zip

<ipython-input-4-f9de91239a30>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)

https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_202210.zip

<ipython-input-4-f9de91239a30>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)

https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_202209.zip

<ipython-input-4-f9de91239a30>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)

https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_202208.zip

<ipython-input-4-f9de91239a30>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)

https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_202207.zip

<ipython-input-4-f9de91239a30>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)

https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_202206.zip

<ipython-input-4-f9de91239a30>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)

https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_202205.zip

<ipython-input-4-f9de91239a30>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)

https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_202204.zip

<ipython-input-4-f9de91239a30>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df)

In [ ]:
df_all.to_csv('/content/drive/MyDrive/df_today.csv', sep=',')

In [ ]:
df_all = pd.read_csv("/content/drive/MyDrive/df_today.csv", sep=',')

<ipython-input-6-60b56805cad7>:1: DtypeWarning: Columns (29,33,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df_all = pd.read_csv("/content/drive/MyDrive/df_today.csv", sep=',')

In [ ]:
# exlui Crypto Opicional
keep_crypto = True
if keep_crypto == True :
    df_cap = df_all.copy()
else :
    df_cap = df_all[~df_all['CNPJ_FUNDO'].isin(names[names['CRYPTO']]['CNPJ_FUNDO'])]

# corta dias com queda grande de count de CNPJS
df_days = df_cap.groupby(['DT_COMPTC'], as_index=False).count()
df_days['Count_pct'] = df_days['CNPJ_FUNDO'].pct_change()
df_days = df_days.loc[df_days['Count_pct'] >= -0.01]
df_days = df_days['DT_COMPTC'].unique()
df_cap = df_cap[df_cap['DT_COMPTC'].isin(df_days)]

In [ ]:
def norm_lb_lf(tab,cap):

    mask = tab.iloc[:, -lb_days:].max(axis=1)-tab.iloc[:, -lb_days:].min(axis=1) > cap

    tab = tab[mask]
    max_lf = tab['lf_val'].quantile(.90).mean()
    min_lf = tab['lf_val'].quantile(.10).mean()
    output = ((tab['lf_val']-min_lf)/(max_lf-min_lf)).clip(0,1).values
    output = tab['lf_val'].values

    max_lb = tab.iloc[:, -lb_days:].quantile(.90).mean()
    min_lb = tab.iloc[:, -lb_days:].quantile(.10).mean()
    input = ((tab.iloc[:, -lb_days:]-min_lb)/(max_lb-min_lb)).clip(0,1).values
    input = tab.iloc[:, -lb_days:].values
    

    return input, output
#############################
lf_gap = 1
lf_days = 20
lb_gap = 2
lb_days = 20

df_ini = df_cap.copy()

# enriquece
df_ini = df_ini[['CNPJ_FUNDO','DENOM_SOCIAL', 'VL_QUOTA','DT_COMPTC']]
df_ini['DT_COMPTC'] = pd.to_datetime(df_ini['DT_COMPTC'])
df_ini['Card'] = df_ini['DT_COMPTC'].rank(ascending=False, method='dense')
df_ini['year'] = df_ini['DT_COMPTC'].dt.year
df_ini.sort_values(by=['CNPJ_FUNDO', 'DT_COMPTC'], inplace=True) 

# input e output
df_ini['lf_val'] = df_ini.groupby('CNPJ_FUNDO')['VL_QUOTA'].shift(-(lf_gap+lf_days))/df_ini.groupby('CNPJ_FUNDO')['VL_QUOTA'].shift(-lf_gap) -1
for i in range(lb_gap,lb_gap+lb_days) :
    df_ini['lb'+str(i)] = df_ini.groupby('CNPJ_FUNDO')['VL_QUOTA'].shift(i)/df_ini.groupby('CNPJ_FUNDO')['VL_QUOTA'].shift(i+1) - 1

In [ ]:
mask1 = df_ini.iloc[:, -lb_days-1:].isna().sum(axis=1)==0
mask2 = df_ini.iloc[:, -lb_days-1:].eq(np.inf).sum(axis=1)==0
mask3 = df_ini.iloc[:, -lb_days-1:].eq(-np.inf).sum(axis=1)==0
mask4 = df_ini.iloc[:, -lb_days-1:].eq(-1).sum(axis=1)==0
mask5 = df_ini.iloc[:, -lb_days-1:].eq(0).sum(axis=1)<=2
df_clean = df_ini[mask1 & mask2 & mask3 & mask4 & mask5]
df_clean['Card'] = df_clean['DT_COMPTC'].rank(ascending=False, method='dense')

<ipython-input-9-d544a985e77b>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Card'] = df_clean['DT_COMPTC'].rank(ascending=False, method='dense')

In [ ]:
model = Sequential()
l_rate = 0.001
thresholds = -50
alphas = 10
from keras import backend as K
model.add(Conv1D(filters=32, kernel_size=6, activation=lambda x: K.relu(x, alpha=alphas, threshold=thresholds), input_shape=(lb_days, 1)))
model.add(MaxPooling1D(pool_size=2))
model.add(Conv1D(filters=64, kernel_size=5, activation=lambda x: K.relu(x, alpha=alphas, threshold=thresholds)))
model.add(Flatten())
model.add(Dense(500, activation=lambda x: K.relu(x, alpha=alphas, threshold=thresholds)))
model.add(Dropout(0.3))
model.add(Dense(250, activation=lambda x: K.relu(x, alpha=alphas, threshold=thresholds)))
model.add(Dropout(0.3))
model.add(Dense(100, activation=lambda x: K.relu(x, alpha=alphas, threshold=thresholds)))
model.add(Dropout(0.3))
model.add(Dense(50, activation=lambda x: K.relu(x, alpha=alphas, threshold=thresholds)))
model.add(Dropout(0.3))
model.add(Dense(25, activation=lambda x: K.relu(x, alpha=alphas, threshold=thresholds)))
model.add(Dropout(0.3))
model.add(Dense(10, activation=lambda x: K.relu(x, alpha=alphas, threshold=thresholds)))
model.add(Dropout(0.3))
model.add(Dense(5, activation=lambda x: K.relu(x, alpha=alphas, threshold=thresholds)))
model.add(Dense(1, activation=lambda x: K.relu(x, alpha=alphas, threshold=thresholds)))

model.compile(optimizer = keras.optimizers.Adamax(learning_rate=l_rate), loss = tf.keras.losses.MeanSquaredError())
weights = model.get_weights()

In [ ]:
# model = Sequential()
# l_rate = 0.01
# alphas = 10
# from keras import backend as K
# model.add(Conv1D(filters=32, kernel_size=6, activation='elu', input_shape=(lb_days, 1)))
# model.add(MaxPooling1D(pool_size=2))
# model.add(Conv1D(filters=64, kernel_size=5, activation='elu'))
# model.add(Flatten())
# model.add(Dense(500, activation='elu'))
# model.add(Dropout(0.3))
# model.add(Dense(250, activation='elu'))
# model.add(Dropout(0.3))
# model.add(Dense(100, activation='elu'))
# model.add(Dropout(0.3))



# model.add(Dense(50, activation='elu'))
# model.add(Dropout(0.3))
# model.add(Dense(25, activation='elu'))
# model.add(Dropout(0.3))
# model.add(Dense(10, activation='elu'))
# model.add(Dropout(0.3))
# model.add(Dense(5, activation='elu'))
# model.add(Dense(1, activation='elu'))

# model.compile(optimizer = keras.optimizers.Adamax(learning_rate=l_rate), loss = tf.keras.losses.MeanSquaredError())
# # weights = model.get_weights()

In [ ]:
past_len = 120
# model.set_weights(weights)

training = df_clean[df_clean['Card']<past_len]
training_input, training_output = norm_lb_lf(training,0)
history = model.fit(training_input, 
                    training_output, 
                    epochs=1,
                    batch_size=1000, 
                    verbose=1)

150/150 [==============================] - 16s 86ms/step - loss: 0.0029

In [ ]:
df_today = df_all[df_all['DT_COMPTC']!=df_all['DT_COMPTC'].max()]

# enriquece
df_today = df_today[['CNPJ_FUNDO','DENOM_SOCIAL','Banco', 'VL_QUOTA','DT_COMPTC']]
df_today['DT_COMPTC'] = pd.to_datetime(df_today['DT_COMPTC'])
df_today.sort_values(by=['CNPJ_FUNDO', 'DT_COMPTC'], inplace=True) 

# input e output
week_day = 5
for i in range(6) :
    df_today['lb_acc'+str(5+i*5)] = (((df_today.groupby('CNPJ_FUNDO')['VL_QUOTA'].shift(0)/df_today.groupby('CNPJ_FUNDO')['VL_QUOTA'].shift(i*week_day+week_day))**(20/(i*week_day+week_day)) - 1)*100).round(2)
for i in range(6) :
    df_today['lb_spot'+str(5+i*5)] = (((df_today.groupby('CNPJ_FUNDO')['VL_QUOTA'].shift(i*week_day)/df_today.groupby('CNPJ_FUNDO')['VL_QUOTA'].shift(i*week_day+week_day))**(20/week_day) - 1)*100).round(2)
df_today = df_today[df_today['DT_COMPTC']==df_today['DT_COMPTC'].max()].drop(['VL_QUOTA'], axis=1)

In [ ]:
df_predict = df_all[df_all['DT_COMPTC']!=df_all['DT_COMPTC'].max()]

# enriquece
df_predict = df_predict[['CNPJ_FUNDO','DENOM_SOCIAL','Banco', 'VL_QUOTA','DT_COMPTC']]
df_predict['DT_COMPTC'] = pd.to_datetime(df_predict['DT_COMPTC'])
df_predict['Card'] = df_predict['DT_COMPTC'].rank(ascending=False, method='dense')
df_predict['year'] = df_predict['DT_COMPTC'].dt.year
df_predict.sort_values(by=['CNPJ_FUNDO', 'DT_COMPTC'], inplace=True) 

lb_days = 20
# input e output
df_predict['lf_val'] = df_predict.groupby('CNPJ_FUNDO')['VL_QUOTA'].shift(-(lf_gap+lf_days))/df_predict.groupby('CNPJ_FUNDO')['VL_QUOTA'].shift(-lf_gap) -1
for i in range(lb_days) :
    lb_curr = df_predict.groupby('CNPJ_FUNDO')['VL_QUOTA'].shift(i)/df_predict.groupby('CNPJ_FUNDO')['VL_QUOTA'].shift(i+1) - 1
    df_predict['lb'+str(i)] = lb_curr

df_predict = df_predict[df_predict['DT_COMPTC']==df_predict['DT_COMPTC'].max()]

# predict_input, predict_output = norm_lb_lf(df_predict,0)
predict_input = df_predict.iloc[:, -lb_days:].values

predictions = model.predict(predict_input,verbose=1)
df_predict['predictions'] = predictions
df_predict = df_predict[['CNPJ_FUNDO','predictions','lb0','lb1','lb2']]
df_today_plus = df_today.merge(df_predict, on='CNPJ_FUNDO', how='left')
display(df_today_plus)

<ipython-input-17-30ebb8865829>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_predict['DT_COMPTC'] = pd.to_datetime(df_predict['DT_COMPTC'])
<ipython-input-17-30ebb8865829>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_predict['Card'] = df_predict['DT_COMPTC'].rank(ascending=False, method='dense')
<ipython-input-17-30ebb8865829>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_predict['year'] = df_predict['DT_COMPTC'].dt.year

39/39 [==============================] - 0s 7ms/step

,CNPJ_FUNDO,DENOM_SOCIAL,Banco,DT_COMPTC,lb_acc5,lb_acc10,lb_acc15,lb_acc20,lb_acc25,lb_acc30,lb_spot5,lb_spot10,lb_spot15,lb_spot20,lb_spot25,lb_spot30,predictions,lb0,lb1,lb2
0,00.398.561/0001-90,PORTO ALISIOS FUNDO DE INVESTIMENTO EM COTAS D...,XP,2023-03-27,-1.93,-5.78,-6.96,-7.95,-8.98,-6.86,-1.93,-9.49,-9.26,-10.87,-12.97,4.51,-0.001293,0.011176,0.018030,-0.028402
1,00.400.490/0001-13,PORTO SEGURO MACRO FUNDO DE INVESTIMENTO EM CO...,XP/BTG,2023-03-27,0.30,-1.46,-0.94,-0.67,-0.43,0.11,0.30,-3.19,0.11,0.12,0.56,2.86,0.000760,0.000482,0.000283,-0.005386
2,00.601.692/0001-23,FAMA FUNDO DE INVESTIMENTO EM COTAS DE FUNDOS ...,XP/BTG,2023-03-27,-8.25,-12.13,-5.00,-7.51,-9.21,-7.15,-8.25,-15.84,11.04,-14.67,-15.69,3.85,-0.005079,0.000071,0.022287,-0.036866
3,00.817.677/0001-17,WESTERN ASSET ALPHA CREDIT RENDA FIXA FUNDO DE...,BTG,2023-03-27,2.04,1.57,1.33,1.10,0.98,0.80,2.04,1.10,0.84,0.42,0.52,-0.09,0.000651,-0.000296,0.000431,0.000329
4,00.819.889/0001-33,WESTERN ASSET HEDGE DÓLAR FUNDO DE INVESTIMENT...,XP,2023-03-27,-1.96,-0.98,1.47,0.98,0.50,-0.12,-1.96,0.02,6.56,-0.49,-1.37,-3.18,0.001278,-0.007351,-0.006563,0.014576
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1240,49.429.025/0001-02,LUXOR MANGALARGA II FI EM COTAS DE FUNDOS DE I...,BTG,2023-03-27,-1.74,-1.44,0.54,-3.03,-3.16,-3.05,-1.74,-1.15,4.62,-13.00,-3.65,-2.51,0.000980,-0.006020,-0.004107,0.010212
1241,49.624.023/0001-66,PS CASH VI INCENTIVADOS FUNDO INCENTIVADO DE I...,BTG,2023-03-27,1.01,1.01,1.01,1.10,NaN,NaN,1.01,1.01,1.01,1.35,NaN,NaN,0.000818,0.000504,0.000502,0.000503
1242,49.731.753/0001-66,AUGME ESTRATÉGICO II FUNDO DE INVESTIMENTO REN...,BTG,2023-03-27,2.20,1.41,NaN,NaN,NaN,NaN,2.20,0.63,NaN,NaN,NaN,NaN,NaN,0.001159,-0.000624,0.001582
1243,49.793.563/0001-73,M M CA MULTIMERCADO CRÉDITO PRIVADO FI EM COTA...,BTG,2023-03-27,1.20,1.19,NaN,NaN,NaN,NaN,1.20,1.19,NaN,NaN,NaN,NaN,NaN,0.000592,0.000593,0.000592
1244,56.824.857/0001-80,ALFAMAIS - FUNDO DE INVESTIMENTO EM COTAS DE F...,BTG,2023-03-27,-4.24,-6.55,-5.99,-6.64,-8.45,-6.53,-4.24,-8.81,-4.87,-8.56,-15.35,3.72,-0.001057,0.009160,0.008975,-0.021332

In [ ]:
df_predict['predictions'] = predictions
df_today_plus = df_today.merge(df_predict, on='CNPJ_FUNDO', how='left')
# display(df_today_plus)

cap = -5
capspot = -1

mask = (df_today_plus['DENOM_SOCIAL'].str.contains("COIN") |
df_today_plus['DENOM_SOCIAL'].str.contains("CRIPTO") |
df_today_plus['DENOM_SOCIAL'].str.contains("CRYPTO") |
df_today_plus['DENOM_SOCIAL'].str.contains("HASHDEX") |
df_today_plus['DENOM_SOCIAL'].str.contains("BLOCK") |
df_today_plus['DENOM_SOCIAL'].str.contains("NFT") |
df_today_plus['DENOM_SOCIAL'].str.contains("CHAIN") |
df_today_plus['DENOM_SOCIAL'].str.contains("PRATA") |
df_today_plus['DENOM_SOCIAL'].str.contains("BTC") |
df_today_plus['DENOM_SOCIAL'].str.contains("OURO")

)


display(df_today_plus[
        (df_today_plus['lb_spot5']>-5.0) &
        (df_today_plus['lb_spot10']>-5.0) &
        (df_today_plus['lb_spot15']>-5.0) ])

# display(df_today_plus[~mask])

,CNPJ_FUNDO,DENOM_SOCIAL,Banco,DT_COMPTC,lb_acc5,lb_acc10,lb_acc15,lb_acc20,lb_acc25,lb_acc30,lb_spot5,lb_spot10,lb_spot15,lb_spot20,lb_spot25,lb_spot30,predictions,lb0,lb1,lb2
1,00.400.490/0001-13,PORTO SEGURO MACRO FUNDO DE INVESTIMENTO EM CO...,XP/BTG,2023-03-27,0.30,-1.46,-0.94,-0.67,-0.43,0.11,0.30,-3.19,0.11,0.12,0.56,2.86,0.000760,0.000482,0.000283,-0.005386
3,00.817.677/0001-17,WESTERN ASSET ALPHA CREDIT RENDA FIXA FUNDO DE...,BTG,2023-03-27,2.04,1.57,1.33,1.10,0.98,0.80,2.04,1.10,0.84,0.42,0.52,-0.09,0.000651,-0.000296,0.000431,0.000329
4,00.819.889/0001-33,WESTERN ASSET HEDGE DÓLAR FUNDO DE INVESTIMENT...,XP,2023-03-27,-1.96,-0.98,1.47,0.98,0.50,-0.12,-1.96,0.02,6.56,-0.49,-1.37,-3.18,0.001278,-0.007351,-0.006563,0.014576
5,00.836.263/0001-35,BV EAGLE RENDA FIXA LONGO PRAZO FUNDO DE INVES...,XP/BTG,2023-03-27,1.13,1.08,1.49,1.13,1.06,1.08,1.13,1.04,2.32,0.07,0.78,1.19,0.000690,0.000767,0.000651,0.000325
6,00.840.011/0001-80,BTG PACTUAL YIELD DI FUNDO DE INVESTIMENTO REN...,BTG,2023-03-27,1.04,1.04,1.04,1.04,1.03,1.02,1.04,1.05,1.03,1.03,1.02,0.96,0.000798,0.000535,0.000510,0.000520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1235,48.263.105/0001-60,CLARITAS LIQUIDEZ FI EM COTAS DE FUNDOS DE INV...,BTG,2023-03-27,0.85,0.86,0.88,NaN,NaN,NaN,0.85,0.87,0.93,NaN,NaN,NaN,NaN,0.000392,0.000446,0.000435
1237,49.304.814/0001-09,BTGP ACCESS BALANCEADO G FI EM COTAS DE FUNDOS...,BTG,2023-03-27,1.24,-0.18,0.23,NaN,NaN,NaN,1.24,-1.59,1.05,NaN,NaN,NaN,NaN,0.000446,0.002158,-0.001641
1238,49.307.394/0001-14,AUTOINVEST GLOBAL BALANCED USD FUNDO DE INVEST...,BTG,2023-03-27,0.06,2.78,2.29,2.07,-0.08,-1.22,0.06,5.56,1.32,1.42,-8.24,-6.74,0.000086,-0.006352,-0.011444,0.020918
1240,49.429.025/0001-02,LUXOR MANGALARGA II FI EM COTAS DE FUNDOS DE I...,BTG,2023-03-27,-1.74,-1.44,0.54,-3.03,-3.16,-3.05,-1.74,-1.15,4.62,-13.00,-3.65,-2.51,0.000980,-0.006020,-0.004107,0.010212
1241,49.624.023/0001-66,PS CASH VI INCENTIVADOS FUNDO INCENTIVADO DE I...,BTG,2023-03-27,1.01,1.01,1.01,1.10,NaN,NaN,1.01,1.01,1.01,1.35,NaN,NaN,0.000818,0.000504,0.000502,0.000503